version: '3'

services:
  strobe-server:
    image: osowin/winters-visual-sync
    ports:
      - "42187:42187"
    volumes:
    # Mount to the ssl folder in the container
      - /etc/letsencrypt/ssl/csr:/app/ssl/csr
      - /etc/letsencrypt/ssl/keys:/app/ssl/keys
    environment:
    # Filename IMPORTANT
      - CERTFILE=/app/ssl/csr/0000_csr-certbot.pem
      - KEYFILE=/app/ssl/keys/0000_key-certbot.pem
