version: '3'

services:
  strobe-server:
    image: osowin/winters-visual-sync
    privileged: true
    ports:
      - "42187:42187"
    volumes:
    # Mount to the ssl folder in the container
      - /etc/letsencrypt/:/app/ssl
    environment:
    # Filename IMPORTANT
      - CERTFILE=/app/ssl/live/kleukerstinkt.me/fullchain.pem
      - KEYFILE=/app/ssl/live/kleukerstinkt.me/privkey.pem
